### ISSUE TITLE
npm scripts 整備

### ISSUE THREAD

**Issue by mpyw** [mpyw/aws-lambda-billing-slack-notification#6]
https://github.com/mpyw/aws-lambda-billing-slack-notification/pull/5#issuecomment-419343832

AWS Lambda デプロイ関連

**Comment by gaogao-9** [comment]
webpack入れる予定ある？私は入れたい派なんだけど

**Comment by miyabisun** [comment]
なんでLambdaでWebpack入れるのかちょっと意味がわかりませんが

**Comment by gaogao-9** [comment]
僕は入れてることもわりとあって、distをzipしてデプロイすると、import/exportシンタックスとかも使えて便利だよみたいな

**Comment by gaogao-9** [comment]
あとawsのラムダバージョンってじわじわ上がるので、上がった瞬間envのターゲット変えるだけで対応できたりして便利なので、babelは少なくとも入れてたほうが絶対良い
