### ISSUE TITLE
config.js を config.default.js からコピーしてくるようにする + 環境変数対応

### ISSUE THREAD

**Issue by mpyw** [mpyw/aws-lambda-billing-slack-notification#7]
- コピー作成する npm script を定義
- ZIPアーカイブデプロイするときには `config.default.js` は除外する
- Git管理から `config.js` は除外する

**Comment by potato4d** [comment]
環境変数から引き回してくるほうが良い気がしているけれど、どうだろう

**Comment by miyabisun** [comment]
出来る限り環境変数から持ってくる設計にすべきでしょうね。
https://dev.classmethod.jp/cloud/aws/aws-lambda-env-variables/

現状YAMLではなくconfig.jsなんで、宣言しなくてもデフォルト設定で動いてくれるようなものは`process.env.HOGE || 'default-value'`みたいな感じにしておくのが良いんじゃないかと思います。

**Comment by mpyw** [comment]
なるほど Lambda にも環境変数機能やっぱりあるんですね…
であればそっちのほうが良さそうですね

**Comment by mpyw** [comment]
但し，項目自体が増減する，サービスエイリアスや絵文字のマッピングなどに関しては環境変数でやるとちょっとつらい気がするので，併用のほうがいいんじゃないかと思いました。

Slackのチャンネルとかエンドポイントはもちろん環境変数から取れる感じのほうがベター

**Comment by gaogao-9** [comment]
localstackの利用するサービスを制限するやつ環境変数で設定できるけどカンマ区切りで特に苦もなく出来てしまったので、設計次第では環境変数で普通に行けそう

**Comment by gaogao-9** [comment]
https://github.com/localstack/localstack#configurations

これの `SERVICES` の変数の指定が参考になります（バリューに指定するサービス名をaws-cliの値を利用している点なども含めて）

**Comment by mpyw** [comment]
なるほど！
